// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/leafney/seine/config"
	"github.com/leafney/seine/internal/api"
	"github.com/leafney/seine/internal/biz"
	"github.com/leafney/seine/internal/dao"
	"github.com/leafney/seine/pkg/gormx"
)

// Injectors from wire.go:

func InitApp() (*App, func(), error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	dbService := gormx.NewDBService(configConfig)
	memoDao := dao.NewMemoDao(dbService)
	memoBiz := biz.NewMemoBiz(memoDao)
	memoApi := api.NewMemoApi(memoBiz)
	app := NewApp(memoApi)
	return app, func() {
	}, nil
}
