// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/leafney/seine/config"
	"github.com/leafney/seine/internal/api"
	"github.com/leafney/seine/internal/biz"
	"github.com/leafney/seine/internal/dao"
	"github.com/leafney/seine/pkg/gormx"
	"github.com/leafney/seine/pkg/xlogx"
)

// Injectors from wire.go:

func InitApp(stop chan struct{}) (*Injector, func(), error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	xLogSvc := xlogx.NewXLogSvc(configConfig)
	gormDBSvc := gormx.NewGormDBSvc(configConfig, xLogSvc, stop)
	memoDao := dao.NewMemoDao(gormDBSvc)
	memoBiz := biz.NewMemoBiz(memoDao)
	memoApi := api.NewMemoApi(memoBiz)
	defRouter := DefRouter{
		DB:      gormDBSvc,
		memoApi: memoApi,
	}
	injector := &Injector{
		L: xLogSvc,
		R: defRouter,
	}
	return injector, func() {
	}, nil
}
